#define ledPin 13
#define speakerPin 11
#define rightButtonPin 2
#define leftButtonPin 4
#define ledBit0Pin 7
#define ledBit1Pin 8
#define ledBit2Pin 9
#define ledBit3Pin 10
#define isDebugging false
#define leftPotPin 0
#define midPotPin 1
#define rightPotPin 2
